/**
 * Cordova Config
 */
import { ICordovaConfigImage } from "./ICordovaConfigImage";
import { ICordovaConfigPreference } from "./ICordovaConfigPreference";

export interface ICordovaConfig {
    widget: {
        $?: {
            id?: string;
            version?: string;
        };
        name?: string;
        description?: string;
        author?: {
            $?: { name?: string; email?: string; href?: string};
            _?: string;
        }[];
        preference?: ICordovaConfigPreference[];
        platform?: {
            $?: { name?: string };
            icon?: ICordovaConfigImage[];
            splash?: ICordovaConfigImage[];
        }[];
    };
}

// Generated by UniteJS
