/**
 * SystemJS Config
 */
export interface ISystemJsConfig {
    baseURL: string;
    transpiler: string;
    paths: { [id: string]: string };
    packages: { [id: string]: { defaultExtension?: string; main?: string } };
    map: { [id: string]: string };
    meta: { [id: string]: { format?: string; loader?: string } };
}

// Generated by UniteJS
