/**
 * Unite Theme Configuration
 */
export interface IUniteThemeConfiguration {
    title: string;
    shortName: string;
    namespace: string;
    organization: string;
    copyright: string;
    webSite: string;
    metaAuthor: string;
    metaAuthorEmail: string;
    metaAuthorWebSite: string;
    metaDescription: string;
    metaKeywords: string[];
    customHeaders: string[];
    themeHeaders: string[];
    backgroundColor: string;
    themeColor: string;
    cordova: string[];
}

// Generated by UniteJS
