/**
 * Unite Client Package Transpile
 */
export interface IUniteClientPackageTranspile {
    alias: string;
    sources?: string[];
    language?: string;
    modules?: string[];
    stripExt?: boolean;
    transforms?: { [id: string]: string };
}

// Generated by UniteJS
