/**
 * Unite Www Directories
 */
export interface IUniteWwwDirectories {
    src: string;
    dist: string;

    unitTest: string;
    unitTestSrc: string;
    unitTestDist: string;

    cssSrc: string;
    cssDist: string;

    e2eTest: string;
    e2eTestSrc: string;
    e2eTestDist: string;

    reports: string;
    package: string;
    build: string;

    assets: string;
    assetsSrc: string;

    configuration: string;
}

// Generated by UniteJS
