/**
 * Unite Build Configuration
 */
export interface IUniteBuildConfiguration {
    name: string;
    bundle: boolean;
    minify: boolean;
    sourcemaps: boolean;
    pwa: boolean;
}

// Generated by UniteJS
