/**
 * Unite Directories
 */
import { IUniteWwwDirectories } from "./IUniteWwwDirectories";

export interface IUniteDirectories {
    wwwRoot: string;
    packagedRoot: string;
    platformRoot: string;

    www: IUniteWwwDirectories;
}

// Generated by UniteJS
