/**
 * Gulp tasks for linting css.
 */
import * as gulp from "gulp";
import * as sassLint from "gulp-sass-lint";
import * as path from "path";
import * as streamToPromise from "stream-to-promise";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-css-lint-app", async () => {
    display.info("Running", "SassLint for App");

    const uniteConfig = await uc.getUniteConfig();

    return streamToPromise(gulp.src(path.join(uniteConfig.dirs.www.cssSrc, `**/*.${uniteConfig.styleExtension}`))
        .pipe(sassLint())
        .pipe(sassLint.format())
        .pipe(sassLint.failOnError())
        .on("error", (err) => {
            display.error("SassLint failed", err);
            process.exit(1);
        }));
});

// Generated by UniteJS
