/**
 * Child class.
 */
import {SYNTHETIC_IMPORT}Vue from "vue";
import Component from "vue-class-component";
import "./child.css";
import {SYNTHETIC_IMPORT}importedTemplate from "./child.vue";

@Component({
    template: importedTemplate
})
export class Child extends Vue {
    public message: string;

    constructor() {
        super();
        this.message = "Hello UniteJS World!";
    }
}

// Generated by UniteJS
