/**
 * Main application class.
 */
import {BrowserRouter, Route} from "react-router-dom";
import {Child} from "./child/child";
import {SYNTHETIC_IMPORT}React from "react";
import {SYNTHETIC_IMPORT}ReactDOM from "react-dom";

export class App {
    run (rootElement) {
        ReactDOM.render(
            <BrowserRouter>
                <Route path="/" component={Child} />
            </BrowserRouter>,
            rootElement
        );
    }
}

/* Generated by UniteJS */
