/**
 * Tests for Bootstrapper.
 */
import * as chaiModule from "chai";
const chai = (chaiModule as any).default || chaiModule;
import { bootstrap } from "../../../src/bootstrapper";

describe("Bootstrapper", () => {
    it("should contain bootstrap", () => {
        chai.should().exist(bootstrap);
    });
});

// Generated by UniteJS
