<template>
    <div>
        <router-view></router-view>
        <hr/>
        <nav>
            <router-link to="/">Child</router-link>
        </nav>
    </div>
</template>
<!-- Generated by UniteJS -->