/**
 * Child class.
 */
import {Component, h} from "preact";
import "./child.css";

export class Child extends Component {
    render () {
        return (<span className="child">Hello UniteJS World!</span>);
    }
}

/* Generated by UniteJS */
