/**
 * Child class.
 *
 * @export
 * @class Child
 */
import {Component, h} from "preact";
import "./child.css";

export class Child extends Component {
    /**
     * Message displayed in the view.
     * @type {string}
     */
    message;

    /**
     * Creates an instance of Child
     */
    constructor() {
        super();
        this.message = "Hello UniteJS World!";
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    render() {
        return <span className="child">{this.message}</span>;
    }
}

/* Generated by UniteJS */
