/**
 * Main application class.
 *
 * @export
 * @class App
 */
import { h, render } from "preact";
import { Link, Router } from "preact-router";
import { Child } from "./child/child";

export class App {
    /**
     * Run the application
     * @param {Element} rootElement
     * @param {string} basePath
     * @returns {void}
     */
    public run(rootElement: Element, basePath: string): void {
        render(<div>
            <Router>
                <Child path={basePath} />
            </Router>
            <hr/>
            <nav>
                <Link href={basePath}>Child</Link>
            </nav>
        </div>,
               rootElement
        );
    }
}

// Generated by UniteJS
