/**
 * Main application class.
 */
import { h, render } from "preact";
import { Router } from "preact-router";
import { Child } from "./child/child";

export class App {
  public run(rootElement: Element): void {
    render(<Router>
      <Child path="/" />
    </Router>,
           rootElement
    );
  }
}

// Generated by UniteJS
