/**
 * Main application class.
 */
import Vue from "vue";
import Component from "vue-class-component";

@Component({
    template: "url:./app.vue"
})
export class App extends Vue {
    constructor() {
        super();
    }
}

// Generated by UniteJS
