/**
 * Main application class.
 *
 * @export
 * @class App
 */
import Vue from "vue";
import Component from "vue-class-component";

@Component({
    template: "./app.vue"
})
export class App extends Vue {
    /**
     * Creates an instance of App.
     */
    constructor() {
        super();
    }
}

// Generated by UniteJS
