/**
 * Main application class.
 */
import {SYNTHETIC_IMPORT}Vue from "vue";
import Component from "vue-class-component";
import {SYNTHETIC_IMPORT}importedTemplate from "./app.vue";

@Component({
    template: importedTemplate
})
export class App extends Vue {
    constructor() {
        super();
    }
}

// Generated by UniteJS
