/**
 * Main entry point for app.
 */
import Vue from "vue";
import { App } from "./app";
import router from "./router";

/**
 * Function to bootstrap the application
 * @returns {Vue}
 */
export function bootstrap(): Vue {
    Vue.config.productionTip = false;

    return new Vue({
        el: "#root",
        router,
        template: "<App/>",
        components: { App }
    });
}

// Generated by UniteJS
