/**
 * Main entry point for app.
 */
import {SYNTHETIC_IMPORT}Vue from "vue";
import { App } from "./app";
import router from "./router";

/**
 * Function to bootstrap the application
 * @returns {Vue}
 */
export function bootstrap(): Vue {
    Vue.config.productionTip = false;

    const innerRootElement = document.createElement("div");
    innerRootElement.id = "innerRoot";

    const root = document.getElementById("root");
    root.appendChild(innerRootElement);

    return new Vue({
        el: "#innerRoot",
        router,
        template: "<App/>",
        components: { App }
    });
}

// Generated by UniteJS
