/**
 * Gulp tasks for linting app with stylint.
 */
import * as gulp from "gulp";
import * as stylint from "gulp-stylint";
import * as path from "path";
import * as streamToPromise from "stream-to-promise";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-css-lint-app", async () => {
    display.info("Running", "Stylint for App");

    const uniteConfig = await uc.getUniteConfig();

    return streamToPromise(gulp.src(path.join(uniteConfig.dirs.www.cssSrc, `**/*.${uniteConfig.styleExtension}`))
        .pipe(stylint({
            reporter: "stylint-stylish"
        }))
        .pipe(stylint.reporter())
        .pipe(stylint.reporter("fail"))
        .on("error", (err) => {
            display.error("Stylint failed", err);
            process.exit(1);
        }));
});

// Generated by UniteJS
