/**
 * Main application class.
 */
import {h, render} from "preact";
import {Router} from "preact-router";
import {Child} from "./child/child";

export class App {
    run (rootElement, basePath) {
        render(<Router>
            <Child path={basePath} />
          </Router>,
            rootElement
        );
    }
}

/* Generated by UniteJS */
