/**
 * Gulp tasks for protractor e2e testing.
 */
import * as gulp from "gulp";
import * as minimist from "minimist";
import * as display from "../../util/display";
import * as exec from "../../util/exec";

gulp.task("e2e-install", async () => {
    display.info("Running", "Webdriver Manager");

    const allDrivers = ["chrome", "firefox", "edge", "ie"];
    const knownOptions = {
        default: {
            drivers: allDrivers.join(",")
        },
        string: [
            "drivers"
        ]
    };

    const options = minimist(process.argv.slice(2), knownOptions);

    const args = ["update"];
    const selectedDrivers = options.drivers.split(",");
    allDrivers.forEach(driver => {
        const driverAndVer = driver.split("@");
        const driverOnly = driverAndVer[0].toLowerCase();
        const actualDriver = driverOnly === "firefox" ? "gecko" : driverOnly;

        args.push(`--${actualDriver}${selectedDrivers.indexOf(driverOnly) >= 0 ? "=true" : "=false"}`);

        if (driverAndVer.length === 2) {
            args.push(`--versions.${actualDriver}=${driverAndVer[1]}`);
        }
    });

    display.info("Args", args);
    try {
        await exec.npmRun("webdriver-manager", args);
    } catch (err) {
        display.error("Executing webdriver-manager", err);
        process.exit(1);
    }
});

// Generated by UniteJS
