/**
 * Main Application Component class.
 */
import { Component } from "@angular/core";

@Component({
  selector: "#root",
  template: `<router-outlet></router-outlet>`
})
export class AppComponent {
}

// Generated by UniteJS
