/**
 * Main Application component Class.
 *
 * @export
 * @class App
 */
import { Component } from "@angular/core";

@Component({
    selector: "#root",
    moduleId: "genModuleId",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"]
})
export class AppComponent {
}

// Generated by UniteJS
