/**
 * Main Application Component class.
 */
import { Component } from "@angular/core";

@Component({
    moduleId: __moduleName || module.id,
    selector: "#root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"]
})
export class AppComponent {
}

// Generated by UniteJS
