/**
 * Main Application module Class.
 *
 * @export
 * @class App
 */
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { RouterModule } from "@angular/router";
import { AppComponent } from "./app.component";
import { ChildComponent } from "./child/child.component";

const appRoutes = [
    { path: "", component: ChildComponent }
];

@NgModule({
    imports: [BrowserModule,
        RouterModule.forRoot(appRoutes)
    ],
    declarations: [
        AppComponent,
        ChildComponent
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}

// Generated by UniteJS
