/**
 * Gulp tasks for producing esdoc documentation.
 */
import * as esdoc from "esdoc";
import * as fs from "fs";
import * as gulp from "gulp";
import * as path from "path";
import * as util from "util";
import * as asyncUtil from "../../util/async-util";
import * as display from "../../util/display";

gulp.task("doc-generate", async () => {
    display.info("Generating", "ESDoc");

    const configFile = path.join(process.cwd(), ".esdoc.json");
    const configExists = await asyncUtil.fileExists(configFile);

    let config;
    if (configExists) {
        const configContent = await util.promisify(fs.readFile)(configFile);
        config = JSON.parse(configContent.toString());
    } else {
        config = {};
    }

    esdoc.default.generate(config, (result, cfg) => {
        display.log(result);
    });
});

// Generated by UniteJS
