/**
 * Tests for GitIgnore.
 */
import * as Chai from "chai";
import * as Sinon from "sinon";
import { IFileSystem } from "unitejs-framework/dist/interfaces/IFileSystem";
import { ILogger } from "unitejs-framework/dist/interfaces/ILogger";
import { UniteConfiguration } from "../../../../../dist/configuration/models/unite/uniteConfiguration";
import { EngineVariables } from "../../../../../dist/engine/engineVariables";
import { GitIgnore } from "../../../../../dist/pipelineSteps/content/gitIgnore";
import { FileSystemMock } from "../../fileSystem.mock";

describe("GitIgnore", () => {
    let sandbox: Sinon.SinonSandbox;
    let loggerStub: ILogger;
    let loggerInfoSpy: Sinon.SinonSpy;
    let loggerErrorSpy: Sinon.SinonSpy;
    let fileSystemMock: IFileSystem;
    let uniteConfigurationStub: UniteConfiguration;
    let engineVariablesStub: EngineVariables;

    beforeEach(() => {
        sandbox = Sinon.sandbox.create();
        loggerStub = <ILogger>{};
        loggerStub.info = () => { };
        loggerStub.error = () => { };
        loggerInfoSpy = sandbox.spy(loggerStub, "info");
        loggerErrorSpy = sandbox.spy(loggerStub, "error");

        fileSystemMock = new FileSystemMock();
        uniteConfigurationStub = new UniteConfiguration();

        engineVariablesStub = new EngineVariables();
        engineVariablesStub.setupDirectories(fileSystemMock, "./test/unit/temp");
    });

    afterEach(async () => {
        sandbox.restore();
        await fileSystemMock.directoryDelete("./test/unit/temp");
    });

    it("can be created", () => {
        const obj = new GitIgnore();
        Chai.should().exist(obj);
    });

    describe("initialise", () => {
        it("can fail when exception is thrown on config", async () => {
            fileSystemMock.fileExists = sandbox.stub().throws("error");
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(1);
            Chai.expect(engineVariablesStub.getConfiguration("GitIgnore")).to.be.equal(undefined);
            Chai.expect(loggerErrorSpy.args[0][0]).contains("failed");
        });

        it("can fail when exception is thrown on ignore", async () => {
            fileSystemMock.fileExists = sandbox.stub().throws("error");
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(1);
            Chai.expect(engineVariablesStub.getConfiguration("ESLint")).to.be.equal(undefined);
            Chai.expect(loggerErrorSpy.args[0][0]).contains("failed");
        });

        it("can succeed when ignore file does not exist", async () => {
            fileSystemMock.fileExists = sandbox.stub().resolves(false);
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(engineVariablesStub.getConfiguration<string[]>("GitIgnore").length).to.be.equal(0);
        });

        it("can succeed when ignore file does exist but forced", async () => {
            engineVariablesStub.force = true;
            fileSystemMock.fileExists = sandbox.stub().resolves(true);
            fileSystemMock.fileReadLines = sandbox.stub().resolves(["dist", "# Generated by UniteJS"]);
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(engineVariablesStub.getConfiguration<string[]>("GitIgnore").length).to.be.equal(0);
        });

        it("can succeed when ignore file does exist", async () => {
            fileSystemMock.fileExists = sandbox.stub().resolves(true);
            fileSystemMock.fileReadLines = sandbox.stub().resolves(["dist", "# Generated by UniteJS"]);
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(engineVariablesStub.getConfiguration<string[]>("GitIgnore").length).to.be.equal(1);
        });

        it("can succeed when ignore file does exist and has blank lines", async () => {
            fileSystemMock.fileExists = sandbox.stub().resolves(true);
            fileSystemMock.fileReadLines = sandbox.stub().resolves(["dist", "", "# Generated by UniteJS", ""]);
            const obj = new GitIgnore();
            const res = await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(engineVariablesStub.getConfiguration<string[]>("GitIgnore").length).to.be.equal(1);
        });
    });

    describe("finalise", () => {
        it("can fail if an exception is thrown", async () => {
            const obj = new GitIgnore();
            const res = await obj.finalise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(1);
            Chai.expect(loggerErrorSpy.args[0][0]).contains("failed");
        });

        it("can skip if file has no generated marker", async () => {
            await fileSystemMock.directoryCreate("./test/unit/temp/www/");
            await fileSystemMock.fileWriteLines("./test/unit/temp/www/", ".gitignore", []);

            const obj = new GitIgnore();
            await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            const res = await obj.finalise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(loggerInfoSpy.args[1][0]).contains("Skipping");
        });

        it("can write if file has a generated marker", async () => {
            await fileSystemMock.directoryCreate("./test/unit/temp/www/");
            await fileSystemMock.fileWriteLines("./test/unit/temp/www/", ".gitignore", ["Generated by UniteJS"]);

            const obj = new GitIgnore();
            await obj.initialise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            const res = await obj.finalise(loggerStub, fileSystemMock, uniteConfigurationStub, engineVariablesStub, true);
            Chai.expect(res).to.be.equal(0);
            Chai.expect(loggerInfoSpy.args[1][0]).contains("Writing");

            const lines = await fileSystemMock.fileReadLines("./test/unit/temp/www/", ".gitignore");
            Chai.expect(lines.length).to.be.equal(3);
        });
    });
});
