/**
 * Gulp tasks for linting components with style lint.
 */
import * as gulp from "gulp";
import * as styleLint from "gulp-stylelint";
import * as path from "path";
import { SyntaxType } from "stylelint";
import * as asyncUtil from "../../util/async-util";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-css-lint-components", async () => {
    display.info("Running", "StyleLint for Components");

    const uniteConfig = await uc.getUniteConfig();

    return asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.src, `**/*.${uniteConfig.styleExtension}`))
        .pipe(styleLint({
            syntax: uniteConfig.styleExtension === "css" ? undefined : <SyntaxType>uniteConfig.styleExtension,
            reporters: [
                { formatter: "string", console: true }
            ]
        }))
        .on("error", (err) => {
            display.error("StyleLint failed", err);
            process.exit(1);
        }));
});

// Generated by UniteJS
