/**
 * Gulp tasks for linting modules.
 */
import * as gulp from "gulp";
import * as eslint from "gulp-eslint";
import * as minimist from "minimist";
import * as path from "path";
import * as streamToPromise from "stream-to-promise";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("e2e-lint", async () => {
    display.info("Running", "ESLint");

    const knownOptions = {
        default: {
            grep: "*"
        },
        string: [
            "grep"
        ]
    };

    const options = minimist(process.argv.slice(2), knownOptions);

    const uniteConfig = await uc.getUniteConfig();

    return streamToPromise(gulp.src(path.join(
        uniteConfig.dirs.www.e2eTestSrc,
        `**/${options.grep}.${uc.extensionMap(uniteConfig.sourceExtensions)}`
    ))
        .pipe(eslint())
        .pipe(eslint.format())
        .pipe(eslint.results(result => {
            if (result.errorCount > 0) {
                process.exit(1);
            }
        })));
});

// Generated by UniteJS
