/**
 * Gulp tasks for protractor e2e testing.
 */
import * as gulp from "gulp";
import * as minimist from "minimist";
import * as install from "selenium-standalone/lib/install";
import * as display from "../../util/display";

gulp.task("e2e-install", async () => {
    display.info("Running", "Selenium Standalone");

    const allDrivers = ["chrome", "firefox", "edge", "ie"];
    const knownOptions = {
        default: {
            drivers: allDrivers.join(",")
        },
        string: [
            "drivers"
        ]
    };

    const options = minimist<{ drivers: string}>(process.argv.slice(2), knownOptions);

    const opts: install.InstallOptions = { drivers: {}};
    const selectedDrivers = options.drivers.split(",").map(selected => selected.split("@"));
    allDrivers.forEach(driver => {
        const foundDriver = selectedDrivers.find(selected => selected[0] === driver);

        if (foundDriver) {
            opts.drivers[driver] = {};

            if (foundDriver.length === 2) {
                opts.drivers[driver].version = foundDriver[1];
            }
        }
    });

    try {
        display.info("Opts", opts);

        opts.logger = (message) => display.log(message);

        await new Promise((resolve, reject) => {
            install(opts, (err) => {
                if (err) {
                    reject(err);
                } else {
                    resolve();
                }
            });
        });
    } catch (err) {
        display.error("Executing selenium-standalone", err);
        process.exit(1);
    }
});

// Generated by UniteJS
