/**
 * Child class.
 */
import * as React from "react";

export class Child extends React.Component {
    public render(): JSX.Element {
        return (<span>Hello UniteJS World!</span>);
    }
}

/* Generated by UniteJS */
