/**
 * Child class.
 */
import React from "react";
import "./child.css";

export class Child extends React.Component {
    public render(): JSX.Element {
        return (<span className="child">Hello UniteJS World!</span>);
    }
}

// Generated by UniteJS
