declare namespace WebdriverIO {
    interface Client<T> {
        loadAndWaitForReactPage(url: string, timeout?: number): Client<T>;
        waitForReactPage(timeout?: number): Client<T>;
    }
}

/* Generated by UniteJS */
