/**
 * Child class.
 */
import {Element as PolymerElement} from "@polymer/polymer/polymer-element";
import childCss from "./child.css";
import childHtml from "./child.html";

export class Child extends PolymerElement {
    static get template (): string {
        return `
        <style>${childCss}</style>
        ${childHtml}`;
    }
}

customElements.define("unite-child", Child);

// Generated by UniteJS
