/**
 * Child class.
 */
import { customElement, property } from "@polymer/decorators/src/decorators";
import { Element as PolymerElement } from "@polymer/polymer/polymer-element";
import {SYNTHETIC_IMPORT}style from "./child.css";
import {SYNTHETIC_IMPORT}template from "./child.html";

@customElement("unite-child")
export class Child extends PolymerElement {
    @property({type: String})
    public message: string;

    constructor() {
        super();
        this.message = "Hello UniteJS World!";
    }

    static get template(): string {
        return `
        <style>${style}</style>
        ${template}`;
    }
}

// Generated by UniteJS
