/**
 * {GEN_NAME_HUMAN} component class.
 */
import {customElement, property} from "@polymer/decorators/src/decorators";
import {Element as PolymerElement} from "@polymer/polymer/polymer-element";
import * as style from "./{GEN_NAME_SNAKE}.css";
import * as template from "./{GEN_NAME_SNAKE}.html";

@customElement("co-{GEN_NAME_SNAKE}")
export class {GEN_NAME_PASCAL} extends PolymerElement {
    @property({type: String})
    public message: string;

    constructor() {
        super();
        this.message = "{GEN_NAME_HUMAN}";
    }

    static get template(): string {
        return `
        <style>${style}</style>
        ${template}`;
    }
}

// Generated by UniteJS
