/**
 * Gulp utils for display.
 */
import * as gutil from "gulp-util";

export function log (text: string): void {
    gutil.log(text);
}

export function info (caption: string, args?: any | any[]): void {
    if (args === undefined) {
        gutil.log(`[${gutil.colors.cyan(caption)}]`);
    } else if (Array.isArray(args)) {
        args.forEach(arg => {
            gutil.log(`[${gutil.colors.cyan(caption)}]`, arg);
        });
    } else {
        gutil.log(`[${gutil.colors.cyan(caption)}]`, args);
    }
}

export function error (text: string, err?: string | Error): void {
    gutil.log(gutil.colors.red(`[ERROR] ${text}`));
    if (err !== undefined) {
        if (err instanceof Error) {
            gutil.log(gutil.colors.red(`${err.message}`));
            if (err.stack) {
                gutil.log(gutil.colors.red(`${err.stack}`));
            }
        } else {
            gutil.log(gutil.colors.red(`${err}`));
        }
    }
}

export function warning (text: string): void {
    gutil.log(gutil.colors.yellow(`[WARNING] ${text}`));
}

export function success (text: string): void {
    gutil.log(gutil.colors.green(text));
}

// Generated by UniteJS
