/**
 * Gulp utils for display.
 */
import * as colors from "ansi-colors";
import * as fancyLog from "fancy-log";

export function log (text: string): void {
    fancyLog(text);
}

export function info (caption: string, args?: any | any[]): void {
    if (args === undefined) {
        fancyLog(`[${colors.cyan(caption)}]`);
    } else if (Array.isArray(args)) {
        args.forEach(arg => {
            fancyLog(`[${colors.cyan(caption)}]`, arg);
        });
    } else {
        fancyLog(`[${colors.cyan(caption)}]`, args);
    }
}

export function error (text: string, err?: string | Error): void {
    fancyLog(colors.red(`[ERROR] ${text}`));
    if (err !== undefined) {
        if (err instanceof Error) {
            fancyLog(colors.red(`${err.message}`));
            if (err.stack) {
                fancyLog(colors.red(`${err.stack}`));
            }
        } else {
            fancyLog(colors.red(`${err}`));
        }
    }
}

export function warning (text: string): void {
    fancyLog(colors.yellow(`[WARNING] ${text}`));
}

export function success (text: string): void {
    fancyLog(colors.green(text));
}

// Generated by UniteJS
