/**
 * Gulp utils for env.
 */

const envUnite: { [id: string]: any } = {};

export function get<T>(name: string): T {
    return <T>envUnite[name];
}

export function set<T>(name: string, value: T): void {
    envUnite[name] = value;
}

// Generated by UniteJS
