/**
 * Gulp utils for package configuration.
 */
import * as fs from "fs";
import * as util from "util";
import { IPackageJson } from "../../types/IPackageJson";
import * as display from "./display";
import * as envUtil from "./env-util";

export async function getPackageJson(): Promise<IPackageJson> {
    let pj = envUtil.get<IPackageJson>("packageJson");

    if (pj) {
        return pj;
    } else {
        try {
            const data = await util.promisify(fs.readFile)("./package.json");
            pj = JSON.parse(data.toString());
            envUtil.set("packageJson", pj);
            return pj;
        } catch (err) {
            display.error("Reading package.json", err);
            process.exit(1);
            return undefined;
        }
    }
}

export async function setPackageJson(packageJson: IPackageJson): Promise<void> {
    try {
        envUtil.set("packageJson", packageJson);
        await util.promisify(fs.writeFile)("./package.json", JSON.stringify(packageJson, undefined, "\t"));
    } catch (err) {
        display.error("Writing package.json", err);
        process.exit(1);
    }
}

// Generated by UniteJS
