
/**
 * Gulp utils for reg ex.
 */
export function toWebUrl (file: string): string {
    return file.replace(/\\/g, "/");
}

export function stripJsExtension (file: string): string {
    return file.replace(/(\.js)$/, "");
}

export function stripLeadingSlash (file: string): string {
    return file.replace(/^\.\//, "");
}

export function replaceLeadingSlash (file: string, replace: string): string {
    return file.replace(/^\.\//, replace);
}

// Generated by UniteJS
