/**
 * Tests for App.
 */
import { expect } from "chai";

describe("App", () => {
    it("the title is set", () => {
        const uniteJson = require("../../../unite.json");
        browser.url("/");
        const title = browser.getTitle();
        expect(title).to.equal(uniteJson.title);
    });

    it("the body text is set", () => {
        browser.url("/");
        const bodyContent = browser.element("body").getText();
        expect(bodyContent).to.equal("Hello TypeScript UniteJS World!");
    });
});

/* Generated by UniteJS */
