/**
 * Tests for App.
 */
/// <reference types="unitejs-webdriver-plugin"/>
import { expect } from "chai";

describe("App", () => {
    it("the title is set", (done) => {
        const uniteThemeJson = require("../../../assetsSrc/theme/unite-theme.json");
        browser
            .uniteLoadAndWaitForPage("/")
            .getTitle()
            .then((title) => {
                expect(title).to.equal(uniteThemeJson.title);
                done();
            });
    });

    it("the child text is set", (done) => {
        browser
            .uniteLoadAndWaitForPage("/")
            .customShadowRoot("#root unite-app::sr iron-pages unite-child::sr span")
            .getText()
            .then((rootContent) => {
                expect(rootContent).to.equal("Hello UniteJS World!");
                done();
            });
    });

    it("the font size is set", (done) => {
        browser
            .uniteLoadAndWaitForPage("/")
            .customShadowRoot("#root unite-app::sr iron-pages unite-child::sr span")
            .getCssProperty("font-size")
            .then((fontSize) => {
                expect(fontSize.value).to.equal("20px");
                done();
            });
    });
});

// Generated by UniteJS
