/**
 * Child class.
 *
 * @export
 * @class Child
 */
import /* Synthetic Import */ React from "react";
import "./child.css";

export class Child extends React.Component {
    /**
     * Message displayed in the view.
     * @type {string}
     */
    message;

    /**
     * Creates an instance of Child
     */
    constructor() {
        super(undefined, undefined);
        this.message = "Hello UniteJS World!";
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    render() {
        return <span className="child">{this.message}</span>;
    }
}

/* Generated by UniteJS */
