/**
 * Child class.
 */
import React, { Component } from "react";

export class Child extends Component {
    render() {
        return (<span>Hello UniteJS World!</span>);
    }
}

/* Generated by UniteJS */
