/**
 * Child class.
 *
 * @export
 * @class Child
 */
import /* Synthetic Import */ React from "react";
import "./child.css";

export class Child extends React.Component {
    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    render () {
        return (<span className="child">Hello UniteJS World!</span>);
    }
}

/* Generated by UniteJS */
