/**
 * Entry point for app.
 */
/// <reference types="unitejs-types" />
import { bootstrap } from "./bootstrapper";

if (window.unite.pwa && "serviceWorker" in navigator) {
    navigator.serviceWorker.register("./service-worker.js")
        .then(
            (registration) => {
                if (!window.unite.bundle) {
                    // tslint:disable-next-line:no-console
                    console.log("ServiceWorker registration successful with scope: ", registration.scope);
                }
                return registration;
            },
            (err) => {
                if (!window.unite.bundle) {
                    // tslint:disable-next-line:no-console
                    console.error("ServiceWorker registration failed: ", err);
                }
            })
        .catch((err) => {
            if (!window.unite.bundle) {
                // tslint:disable-next-line:no-console
                console.error(err);
            }
        });
}

const rootElement = document.getElementById("root");
const loaderHideId = setInterval(
    () => {
        if ((rootElement.innerText && rootElement.innerText.length > 0) ||
            (rootElement.children && rootElement.children.length > 0)) {
            clearInterval(loaderHideId);
            const loaderElement = document.getElementById("app-loader");
            if (loaderElement) {
                loaderElement.parentNode.removeChild(loaderElement);
            }
        }
    },
    10);

if ((window as any).cordova) {
    document.addEventListener("deviceready", () => {
        bootstrap();
    });
} else {
    bootstrap();
}

// Generated by UniteJS
