declare namespace WebdriverIO {
    interface Client<T> {
        loadAndWaitForPage(url: string, timeout?: number): Client<T>;
        waitForPage(timeout?: number): Client<T>;
    }
}

/* Generated by UniteJS */
