/**
 * Main application class.
 */
import "@polymer/app-route/app-location";
import "@polymer/app-route/app-route";
import {Element as PolymerElement} from "@polymer/polymer/polymer-element";
import appHtml from "./app.html";
import "./child/child";

export class App extends PolymerElement {
    static get template (): string {
        return `${appHtml}`;
    }
}

customElements.define("unite-app", App);

// Generated by UniteJS
