/**
 * Gulp tasks for producing jsdoc documentation.
 */
import * as gulp from "gulp";
import * as path from "path";
import * as display from "../../util/display";
import * as exec from "../../util/exec";

gulp.task("doc-generate", async () => {
    display.info("Generating", "JSDoc");

    const configFile = path.join(process.cwd(), ".jsdoc.json");

    return exec.npmRun("jsdoc", ["--verbose", "--configure", configFile])
        .catch((err) => {
            display.error("JSDoc Failed", err);
            process.exit(1);
        });
});

// Generated by UniteJS
