/**
 * Gulp tasks for post building css.
 */
import * as gulp from "gulp";
import * as cssnano from "gulp-cssnano";
import * as rename from "gulp-rename";
import * as path from "path";
import * as through2 from "through2";
import * as asyncUtil from "../../util/async-util";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-css-post-app", async () => {
    display.info("Running", "CSS None for App");

    const uniteConfig = await uc.getUniteConfig();
    const buildConfiguration = uc.getBuildConfiguration(uniteConfig, false);

    await asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.cssDist, "main.css"))
        .pipe(rename("style.css"))
        .pipe(buildConfiguration.minify ? cssnano() : through2.obj())
        .pipe(gulp.dest(uniteConfig.dirs.www.cssDist)));

    if (buildConfiguration.minify) {
        await asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.cssDist, "**/!(style).css"))
            .pipe(cssnano())
            .pipe(gulp.dest(uniteConfig.dirs.www.cssDist)));
    }
});

// Generated by UniteJS
