/**
 * Gulp tasks for post building css.
 */
import * as gulp from "gulp";
import * as cssnano from "gulp-cssnano";
import * as gutil from "gulp-util";
import * as path from "path";
import * as asyncUtil from "../../util/async-util";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-css-post-components", async () => {
    display.info("Running", "CSS None for Components");

    const uniteConfig = await uc.getUniteConfig();
    const buildConfiguration = uc.getBuildConfiguration(uniteConfig, false);

    await asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.dist, "**/*.css"))
        .pipe(buildConfiguration.minify ? cssnano() : gutil.noop())
        .pipe(gulp.dest(uniteConfig.dirs.www.dist)));

    if (buildConfiguration.minify) {
        await asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.dist, "**/*.css"))
            .pipe(cssnano())
            .pipe(gulp.dest(uniteConfig.dirs.www.dist)));
    }
});

// Generated by UniteJS
