/// <reference types="polymer"/>

declare module "@polymer/polymer/polymer-element" {
    export class Element extends HTMLElement implements polymer.Base {
        public is: string;
    }
}

// Generated by UniteJS
