/**
 * Tests for App.
 */
import /* Synthetic Import */ chai from "chai";
import { App } from "../../../src/app";

describe("App", () => {
    it("can be created", () => {
        const app = new App();
        chai.should().exist(app);
    });
});

// Generated by UniteJS
