/**
 * Tests for Bootstrapper.
 */
import /* Synthetic Import */ chai from "chai";
import { bootstrap } from "../../../src/bootstrapper";

describe("Bootstrapper", () => {
    it("should contain bootstrap", () => {
        chai.should().exist(bootstrap);
    });
});

// Generated by UniteJS
