/**
 * Tests for App.
 */
/// <reference types="unitejs-protractor-plugin"/>
import { expect } from "chai";
import { $, browser, by, element } from "protractor";

describe("App", () => {
    it("the title is set", (done) => {
        const uniteThemeJson = require("../../../assetsSrc/theme/unite-theme.json");
        browser.get("/")
            .then(() => {
                browser.getTitle()
                    .then((title) => {
                        expect(title).to.equal(uniteThemeJson.title);
                        done();
                    });
            });
    });

    it("the root text is set", (done) => {
        browser.uniteLoadAndWaitForPage("/")
            .then(() => {
                $("#root").getText()
                    .then((rootContent) => {
                        expect(rootContent).to.equal("Hello UniteJS World!");
                        done();
                    });
            });
    });

    it("the font size is set", (done) => {
        browser.uniteLoadAndWaitForPage("/")
            .then(() => {
                element(by.customShadowRoot("#root unite-app::sr iron-pages unite-child::sr div "))
                    .getCssValue("font-size")
                    .then((fontSize) => {
                        expect(fontSize).to.equal("20px");
                        done();
                    });
            });
    });
});

// Generated by UniteJS
