/**
 * Tests for App.
 */
import { expect } from "chai";
import { browser, by } from "protractor";

describe("App", () => {
    it("the title is set", (done) => {
        const uniteJson = require("../../../unite.json");
        browser.get("/")
            .then(() => {
                browser.getTitle()
                    .then((title) => {
                        expect(title).to.equal(uniteJson.title);
                        done();
                    });
            });
    });

    it("the body text is set", (done) => {
        browser.get("/")
            .then(() => {
                browser.element(by.css("body")).getText()
                    .then((bodyContent) => {
                        expect(bodyContent).to.equal("Hello UniteJS World!");
                        done();
                    });
            });
    });
});

/* Generated by UniteJS */
