/**
 * Gulp tasks for post building css.
 */
import * as gulp from "gulp";
import * as cssnano from "gulp-cssnano";
import * as postcss from "gulp-postcss";
import * as rename from "gulp-rename";
import * as sourcemaps from "gulp-sourcemaps";
import * as gutil from "gulp-util";
import * as path from "path";
import * as asyncUtil from "../../util/async-util";
import * as display from "../../util/display";
import * as errorUtil from "../../util/error-util";
import * as uc from "../../util/unite-config";

gulp.task("build-css-post-app", async () => {
    display.info("Running", "PostCss for App");

    const uniteConfig = await uc.getUniteConfig();
    const buildConfiguration = uc.getBuildConfiguration(uniteConfig, false);

    let errorCount = 0;

    return asyncUtil.stream(gulp.src(path.join(uniteConfig.dirs.www.cssDist, "main.css"))
        .pipe(rename("style.css"))
        .pipe(buildConfiguration.sourcemaps ? sourcemaps.init() : gutil.noop())
        .pipe(postcss())
        .on("error", (err) => {
            display.error(err.message);
            errorCount++;
        })
        .on("error", errorUtil.handleErrorEvent)
        .pipe(buildConfiguration.minify ? cssnano() : gutil.noop())
        .pipe(buildConfiguration.sourcemaps ? sourcemaps.write({
            includeContent: true,
            sourceRoot: "./src"
        }) : gutil.noop())
        .pipe(gulp.dest(uniteConfig.dirs.www.cssDist))
        .on("end", () => {
            errorUtil.handleErrorCount(errorCount);
        }));
});

// Generated by UniteJS
