/**
 * Tests for App.
 */
/// <reference types="unitejs-aurelia-webdriver-plugin"/>

describe("App", () => {
    it("the title is set", () => {
        const uniteJson = require("../../../../unite.json");
        return browser
            .url("/")
            .getTitle()
            .then((title) => {
                expect(title).toEqual(uniteJson.title);
            });
    });

    it("the router text is set", () => {
        return browser
            .loadAndWaitForAureliaPage("/")
            .element("router-view")
            .getText()
            .then((routerContent) => {
                expect(routerContent).toEqual("Hello UniteJS World!");
            });
    });
});

/* Generated by UniteJS */
