/**
 * Gulp tasks for producing documentation.
 */
import * as del from "del";
import * as deleteEmpty from "delete-empty";
import * as gulp from "gulp";
import * as path from "path";
import * as runSequence from "run-sequence";
import * as util from "util";
import * as display from "./util/display";
import * as uc from "./util/unite-config";
require("./doc-generate");

gulp.task("doc-clean", async () => {
    const uniteConfig = await uc.getUniteConfig();
    const docFolder = path.join("../", uniteConfig.dirs.docsRoot);

    const toClean = [
        path.join(docFolder, "**/*")
    ];
    display.info("Cleaning", toClean);
    try {
        await del(toClean, { force: true });
        await util.promisify(deleteEmpty)(docFolder, {
            verbose: false
        });
    } catch (err) {
        display.error(err);
        process.exit(1);
    }
});

gulp.task("doc-build", async () => {
    try {
        await util.promisify(runSequence)("doc-clean", "doc-generate");
    } catch (err) {
        display.error("Unhandled error during task", err);
        process.exit(1);
    }
});

// Generated by UniteJS
