/**
 * Tests for Bootstrapper.
 */
import { bootstrap } from "../../../src/bootstrapper";

describe("Bootstrapper", () => {
    it("should contain bootstrap", (done) => {
        expect(bootstrap).toBeDefined();
        done();
    });
});

// Generated by UniteJS
