/**
 * Main Application Class.
 *
 * @export
 * @class App
 */
import { Router, RouterConfiguration } from "aurelia-router";

export class App {
    public router: Router;

    /**
     * Configure the router.
     * @param {RouterConfiguration} config
     * @param {Router} router
     * @returns {(Promise<void> | PromiseLike<void> | void)}
     */
    public configureRouter(config: RouterConfiguration, router: Router): Promise<void> | PromiseLike<void> | void {
        config.map([
            {
                route: "", name: "child", moduleId: "./child/child"
            }
        ]);

        this.router = router;
    }
}

// Generated by UniteJS
