/**
 * Main entry point for app.
 */
/// <reference types="unitejs-types" />
import { bootstrap as abootstrap } from "aurelia-bootstrapper";
import { Aurelia } from "aurelia-framework";

/**
 * Bootstrap the application.
 * @returns {Promise<void>}
 * @export
 */
export function bootstrap(): Promise<void> {
    return abootstrap((aurelia: Aurelia) => {
        aurelia.use
            .standardConfiguration()
            .plugin("aurelia-dialog")
            .plugin("aurelia-validation");

        if (!window.unite.bundle) {
            aurelia.use.developmentLogging();
        }

        return aurelia.start()
            .then(() => {
                const root = document.getElementById("root");
                aurelia.setRoot("dist/app", root);
                root.setAttribute("aurelia-app", "");
                return aurelia;
            });
    });
}

// Generated by UniteJS
