/**
 * Gulp tasks for wrapping Webpack modules.
 */
import * as gulp from "gulp";

gulp.task("build-bundle-vendor", () => {
    // Vendor bundling is performed as a chunk in build-bundle-app
});

// Generated by UniteJS
