/**
 * Gulp tasks for wrapping Webpack modules.
 */
import * as gulp from "gulp";
import * as path from "path";
import * as webpack from "webpack";
import * as webpackStream from "webpack-stream";
import * as asyncUtil from "../../util/async-util";
import * as clientPackages from "../../util/client-packages";
import * as display from "../../util/display";
import * as uc from "../../util/unite-config";

gulp.task("build-bundle-app", async () => {
    const uniteConfig = await uc.getUniteConfig();

    const buildConfiguration = uc.getBuildConfiguration(uniteConfig, false);

    if (buildConfiguration.bundle) {
        display.info("Running", "Webpack for App");

        const entry: { [id: string]: string | string[] } = {};
        const plugins: webpack.Plugin[] = [];

        const vendorPackages = await clientPackages.getBundleVendorPackages(uniteConfig);

        const vendorKeys: string[] = [];
        const vendorAliases: { [id: string]: string } = {};
        let hasStyleLoader = false;
        Object.keys(vendorPackages).forEach((key) => {
            const idx = key.indexOf("systemjs");
            if (idx < 0) {
                display.info("Adding", `${vendorPackages[key].file}`);
                vendorKeys.push(key);
                vendorAliases[`${key}${vendorPackages[key].useExact ? "$" : ""}`] =
                    path.resolve(`${vendorPackages[key].file}`);
            } else {
                if (!hasStyleLoader) {
                    hasStyleLoader = key === "systemjs-plugin-css";
                }
            }
        });

        if (vendorKeys.length > 0) {
            entry.vendor = vendorKeys;
        }

        plugins.push(new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify(buildConfiguration.minify ? "production" : "development")
            }
        }));

        entry.app = `./${path.join(uniteConfig.dirs.www.dist, "entryPoint.js")}`;

        const newModule: webpack.Module = { rules: [] };

        const webpackOptions: webpack.Configuration = {
            entry,
            output: {
                devtoolModuleFilenameTemplate: "[resource-path]",
                filename: "app-bundle.js",
                chunkFilename: "[name]-bundle.js"
            },
            plugins,
            module: newModule,
            resolve: {
                alias: vendorAliases
            },
            mode: buildConfiguration.minify ? "production" : "development",
            optimization: {
                minimize: buildConfiguration.minify,
                splitChunks: {
                    cacheGroups: {
                        vendor: {
                            chunks: "initial",
                            name: "vendor",
                            test: "vendor",
                            enforce: true
                        }
                    }
                }
            },
            performance: {
                hints: false
            }
        };

        newModule.rules.push({
            test: new RegExp(".css$"),
            use: hasStyleLoader ? ["style-loader", "css-loader"] : ["raw-loader"]
        });

        uniteConfig.viewExtensions.forEach((ext) => {
            newModule.rules.push({
                test: new RegExp(`.${ext}$`),
                use: ["raw-loader"]
            });
        });

        if (buildConfiguration.sourcemaps) {
            webpackOptions.devtool = "inline-source-map";
            newModule.rules.push({
                test: /\.js$/,
                enforce: "pre",
                loader: "source-map-loader"
            });
        }

        return asyncUtil.stream(gulp.src(entry.app)
            .pipe(webpackStream(webpackOptions, webpack))
            .pipe(gulp.dest(uniteConfig.dirs.www.dist)));
    }
});

// Generated by UniteJS
